CREATE DATABASE IF NOT EXISTS autosystem DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE autosystem;

CREATE TABLE IF NOT EXISTS brands (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS models (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  brand_id BIGINT NOT NULL,
  CONSTRAINT fk_model_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vehicles (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  model_id BIGINT NOT NULL,
  year INT NOT NULL,
  color VARCHAR(50),
  mileage BIGINT,
  price DECIMAL(12,2) NOT NULL,
  status VARCHAR(30) NOT NULL,
  CONSTRAINT fk_vehicle_model FOREIGN KEY (model_id) REFERENCES models(id) ON DELETE CASCADE
);
